# Numpy

In [1]:
conda install numpy

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

[1 2 3 4]


In [8]:
import numpy as np

a = np.array([1,2,3])

In [16]:
a

array([1, 2, 3])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [13]:
print(np.arange(4))
print(np.arange(0,10,2)) # Start, Stop, Step

[0 1 2 3]
[0 2 4 6 8]


In [15]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

# Add , Remove , and Sort

In [18]:
arr = np.array([1,2,3,4,5,6,7,8])

In [19]:
np.append(arr,[1,2]) #Add

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [20]:
np.delete(arr,1) #delete

array([1, 3, 4, 5, 6, 7, 8])

In [21]:
arr = np.array([2,1,5,3,7,4,6,8])

In [22]:
np.sort(arr) #urutkan

array([1, 2, 3, 4, 5, 6, 7, 8])

# Shape and Size

In [23]:
array_example = np.array ([[[0,1,2,3],
                            [4,5,6,7]],
                            [[0,1,2,3],
                             [4,5,6,7]],
                             [[0,1,2,3],
                              [4,5,6,7]]])
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [25]:
array_example.ndim # menentukan jumlah axes atau dimensi dari aray

3

In [27]:
array_example.size # menentukan jumlah total elemen dari aray

24

In [29]:
array_example.shape # menampilkan tuple integer jumlah elemen dari aray

(3, 2, 4)

In [30]:
arr_one = np.array([[1,2,3,4,5]])

In [31]:
arr_one.ndim

2

In [32]:
arr_one.size

5

In [33]:
arr_one.shape

(1, 5)

# Reshape

In [34]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [35]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [36]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# Convert 1D to 2D

In [37]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [38]:
# npnewaxis to add a new axis
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [40]:
# Can convert a 1D array to a row vector by inserting an axis
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [41]:
# for a column vector, you can insert an axis along the second dimension

col_vector = a[: , np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [42]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [43]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [44]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# Index and Slicing

In [45]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [46]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [48]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [50]:
#divisible by 2
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [51]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


# Creating Array from Existing Data

In [52]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [53]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [55]:
a_1 = np.array([[1,1],
                [2,2]])

In [56]:
a_2 = np.array([[3,3],
                [4,4]])

In [57]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [58]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [60]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
       [13,14,15,16,17,18,19,20,21,22,23,24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [61]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [62]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic Array operation

In [65]:
a = np.array([1,2,3,4])

a.sum()

10

In [66]:
b = np.array([[1,1], [2,2]])
b

array([[1, 1],
       [2, 2]])

In [67]:
b.sum(axis=0)

array([3, 3])

In [68]:
b.sum(axis=1)

array([2, 4])

In [70]:
data = np.array([1,2])
data

array([1, 2])

In [71]:
ones = np.ones(2)
ones

array([1., 1.])

In [72]:
data + ones

array([2., 3.])

In [73]:
data * data

array([1, 4])

In [74]:
data / data

array([1., 1.])

# Broadcasting

In [75]:
data *2

array([2, 4])

In [76]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [77]:
A.sum()

4.8595784

In [78]:
A.min()

0.05093587

In [79]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [80]:
A.max()

0.82485143

In [81]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [82]:
A.std()

0.21392120766089617

Creatung Matrices

In [83]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.82590516, 0.08273439],
       [0.48097723, 0.56548598],
       [0.7242147 , 0.41899007]])

In [84]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.44755438 0.82730063]
 [0.69856191 0.82885979]
 [0.38792235 0.45903948]]


# Matrix Arithmetic

In [85]:
data = np.array([[1,2],[3,4]])
print(data)

[[1 2]
 [3 4]]


In [86]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [87]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [88]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [90]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


# Dot Product

In [93]:
a_1 = np.array([[1,2,3],
                [4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8],
                [9,10],
                [11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [94]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

# Matrix Indexing

In [95]:
data = np.array([[1,2],
                 [3,4],
                 [5,6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


# Matrix Aggregation

In [96]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [97]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [98]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


# Transporting and Reshaping

In [99]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [100]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [101]:
data_col = np.array([[1,2,3,4,5,6]]) . T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [102]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [104]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


# N-Dimensional Array

In [108]:
ndarr = np.array([[[1,2], [3,4]],
                  [[5,6],[7,8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [109]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [110]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [111]:
print(np.random.random((4,3,2)))

[[[0.52336364 0.4909175 ]
  [0.93152387 0.03203715]
  [0.65956558 0.1915659 ]]

 [[0.7113075  0.41014182]
  [0.37024482 0.03585429]
  [0.53020301 0.94297685]]

 [[0.68857685 0.82541051]
  [0.12630308 0.50208678]
  [0.8313418  0.57997245]]

 [[0.47566444 0.41421868]
  [0.87048212 0.32576109]
  [0.36835407 0.60528417]]]


# Flatten N-Dimensional Array

In [114]:
arrflat = np.array([[1,2,3,4],
                      [5,6,7,8,],
                      [9,10,11,12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [115]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Notes on Numpy Vector

In [2]:
import numpy as np
a = np.random.rand(5)

In [3]:
print(a)

[0.92084575 0.35900323 0.17240094 0.03260281 0.27113623]


In [4]:
a.shape # Rank 1 Array

(5,)

In [5]:
print(a.T)

[0.92084575 0.35900323 0.17240094 0.03260281 0.27113623]


In [6]:
print(np.dot(a, a.T))

1.0811400937253632


In [7]:
a = np.random.rand(5,1) # Column Vector

In [8]:
print(a)

[[0.28960866]
 [0.59745627]
 [0.23981204]
 [0.69406319]
 [0.21201585]]


In [9]:
print(a.T)

[[0.28960866 0.59745627 0.23981204 0.69406319 0.21201585]]


In [10]:
print(np.dot(a, a.T))

[[0.08387318 0.17302851 0.06945164 0.20100672 0.06140163]
 [0.17302851 0.35695399 0.14327721 0.4146724  0.1266702 ]
 [0.06945164 0.14327721 0.05750981 0.16644471 0.05084395]
 [0.20100672 0.4146724  0.16644471 0.48172372 0.1471524 ]
 [0.06140163 0.1266702  0.05084395 0.1471524  0.04495072]]


In [11]:
a = np.random.rand(1,5) # Row Vector

In [12]:
print(a)

[[0.39927884 0.21933222 0.98238864 0.47063284 0.30212666]]
